use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :sthub, StHubWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [host: "testhub.in.fkn.space", port: 443],
  server: true,
  https: [
    port: 443,
    cipher_suite: :strong,
    keyfile: "/home/ec2-user/sthub-web/privkey.pem",
    certfile: "/home/ec2-user/sthub-web/cert.pem",
    transport_options: [socket_opts: [:inet6]]
  ],
  force_ssl: [hsts: true]

# Do not print debug messages in production
config :logger, level: :debug

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
